# Generated by Django 4.1.7 on 2023-03-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=9)),
                ('status', models.CharField(blank=True, choices=[('is_active', 'is_active'), ('is_not_active', 'is_not_active')], max_length=23)),
            ],
        ),
    ]
